---
abstract: 'YAML support for Padre The Perl IDE'
author:
  - 'Zeno Gantner <zenog@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Temp: 0.22
  Locale::Msgfmt: 0.15
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-YAML
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Padre: 0.94
  Try::Tiny: 0.11
  YAML::XS: 0.38
  perl: 5.10.0
resources:
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginYAML
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-YAML
version: 0.05
